version: "3"

services:
    consumer:
      build: ./consumer
      links:
        - redis-aof
        - redis-rdb
        - redis-nopersist
        - beanstalkd-nopersist
        - beanstalkd-persist
      restart: always
      env_file:
        .env
      volumes:
        - "./data:/data"


    producer:
      build: ./producer
      links: 
        - redis-aof
        - redis-rdb
        - redis-nopersist
        - beanstalkd-nopersist
        - beanstalkd-persist
      restart: always
      env_file:
        .env
      volumes:
        - "./data:/data"
      ports:
        - 9000:9000
 

    redis-aof:
        image: redis:6.0-alpine
        command: redis-server /data/redis-aof.conf
        volumes:
          - "./data:/data"

    redis-rdb:
        image: redis:6.0-alpine
        command: redis-server /data/redis-rdb.conf
        volumes:
          - "./data:/data"

    redis-nopersist:
        image: redis:6.0-alpine
        command: redis-server /data/redis-nopersist.conf
        volumes:
          - "./data:/data"

    beanstalkd-persist:
        build: ./beanstalkd
        command: beanstalkd -b /data
        volumes:
          - "./data:/data"

    beanstalkd-nopersist:
        build: ./beanstalkd
        command: beanstalkd
